version: '3.8'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nest_users
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  nestjs-app:
    image: node:latest
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - mysql-container
    networks:
      - app-network

  react-app:
    image: node:latest
    container_name: react-app
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - nestjs-app
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
